### ISSUE TITLE
Make the header stick to the top of page

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#27]
It should not move out of view on page scroll. This is very important in e.g. the course notes, where we scroll at lot (miles down), and we want to keep the ALeA log on the left and (even more importantly) acces to the  profile and help in sync. And while we are at it, I would (at least when it leaves the beginning of the document) make the bar transparent, so that it shows (as much as possible) the text underneith. 

I suspect that a few lines of well-placed CSS3 could fix this. Maybe this is something Rakesh can do.

**Comment by kohlhase** [comment]
@abchugh said this is not trivial because of the TOC bar on the left. Maybe we have to rethink this from a "bar" (which can stay in place for all I care as long as I have a floating "toolbox" on the right that I can always access. It might just initially (i.e. for the start of the course notes) find it's place on the bar, but stay in its place on the top right when the content is scrolled down.

**Comment by abchugh** [comment]
Fixed with 08cc10d
