### ISSUE TITLE
Layout: show the notes and such in a right infobar (notes mode) 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#36]
The notes feature is great, and the greatest part of it is that they are localized. 
To take full advantage of this we need a new layout for the notes where e.g. an icon on the right shows that there are notes present in the current line or paragraph. There is something like that with the vertical `...` for the links and sources. But these overlap the text (that should also be fixed). 
I know I have shown this image a couple of times already, but I still think that the usability of the infobar is much better than we have now. 
![arxivdemo](https://user-images.githubusercontent.com/4037538/208298893-b6ba4032-3ba8-47a3-8394-1056ae7b906d.png)
I am imagining different markers (icons) for different kinds of notes, in particular it would be good if questions would be easily identifiable, so that I can answer them.

**Comment by kohlhase** [comment]
Just to be clear, I do not care about the infobar being marked by a box or so, but just being a non-overlapping space. I expect many of the localized interactions to be keyed there by icons.

**Comment by kohlhase** [comment]
I see that you made an info bar, but I can only see the

**Comment by kohlhase** [comment]
I guess the behavior I would like to see is that the "add a comment" (+) has a hover that also tells users about highlighing 
something like `Add a comment to this slide\\ Selecting a region allows comments localized to the region`. 
And then the postulated info markers  on the right, when 
* hovered:  highlight the comment anchor (the region selected when making the comment) 
* clicked: shows the comment
* double-clicked: showsthe thread. 
or some variant of this.

**Comment by abchugh** [comment]
1. When you add a comment _**and refresh the page**_, the add comment button is replaced by : (1) a blue bubble in case a public comment is added or, (2) a blue list icon when a private note is added.
2. The icon should indeed change immediately after a comment is added, instead of requiring a page reload. I will fix this.

Btw, I pick icons from [here](https://mui.com/material-ui/material-icons). I can easily switch if you like something else better.

**Comment by kohlhase** [comment]
Is there any way around the refresh? I find that I have the AI notes pinned in my browser, so I never refresh.

**Comment by abchugh** [comment]
Your other suggestion has one major issue: Remember that the comments are not completely localized. They are only associated with the sTeX document, not the exact position inside the document. In addition, we currently store a plain text conversion of the HTML element(s) selected at the time when the user made the comment.  This text is shown just above the user's comment.

I wouldn't even be able to (easily) highlight back the HTML element easily even if I stored the HTML element selected at the time when the comment was made. This is because the content is not very stable - both because of actual changes and things like randomized IDs changing each time content is rebuilt.

That being said, I agree that the localization you are looking for is indeed quite important. That would require having a somewhat intelligent algorithm that can work despite minor changes to the content. That feels like a separate issue.

Another thing I can do in the meantime is this: when the user hovers on the blue bubble/list icon, I can show the *first* comment in a hover window (similar to the hovers we do for definitions). 

Let me know what you think.

**Comment by abchugh** [comment]
> Is there any way around the refresh? I find that I have the AI notes pinned in my browser, so I never refresh.

I am going to fix it in a couple of days 😃

**Comment by kohlhase** [comment]
I understand the (I agree separate) issue about the selecting/highlighting. We should think about that. 
I have seen that you can attach the notes to the "semantic units" such as definitions, and that is very good. 
About the selection/highlight, I understand that you keep the plain text of the selection (at least is shows up in the error messages). I would suspect that the text is stable enough that we can find the selection in 95% of the cases. And I am totally OK, if the localization of the comments falls back to the nearest semantic unit if we cannot find it.
