### ISSUE TITLE
help/manual link in all VoLL-KI 

### ISSUE THREAD

**Issue by kohlhase** [slatex/sTeX-React#48]
We have the beginnings of a help/manual document in sTeX (see https://gl.mathhub.info/voll-ki/SSFC/-/blob/main/source/doc/; unfortunately, development is now on the `devel` branch). This is (going to be) a document just like the AI notes or other courses including guided tours and the like. 

Even though this is mostly a placeholder now, it should be linked from all parts of the SSFC front-end, so that students can see what the current feature set is (and understand the concepts behind them). 

I do not really care how the links are made, just that they be there.

**Comment by Jazzpirate** [comment]
More generally: *A* "course portal" (with emphasis on "*a*" rather than "*the*") should be able to determine the list of courses/top-level documents via some kind of configuration. E.g. our current course portal would have the various lecture notes and the above manual for the SSFC platform; a more "mathhub-general" one might also have the smglom as "one giant course", the sTeX-Documentation etc.

**Comment by kohlhase** [comment]
I agree with this, but I consider this a separate issue. The help/manual should be accessible in any front-end we are providing. After all, this is just a standard icon somewhere on the top right.

**Comment by Jazzpirate** [comment]
Ah, that makes sense - but I also foresee that that help section too might be (at least slightly - logos etc.) different for different instances, so making that one configurable rather than hardcoded seems like the right way to go about this ;)

More broadly, I think it would be a good idea to make *all* frontend features and layout schemata as customizable and localized as possible

**Comment by kohlhase** [comment]
That makes a lot of sense, but I would not like this to be on the critical path for getting the help/manual feature into the system.
