### ISSUE TITLE
Remove interactivity on definiendum

### ISSUE THREAD

**Issue by abchugh** [slatex/sTeX-React#5]
Definiendum should not have tooltips, hover-info, and on-click dialogues

**Comment by kohlhase** [comment]
I am not sure that this is the case, I can see some interaction, e.g. showing
* synonyms, hyper/hpyonyms,  
* examples 
* the type
just not the  the same ones as `symref` has.

**Comment by Jazzpirate** [comment]
I've replaced the `symref`-like overlay with the upper part of what one gets if one `clicks` on a `symdecl` (i.e. tex-macro, notations, type, definiens etc.). That way, definienda stay interactive and show information not otherwise available, without showing the same fragment one is (usually) currently looking at already.
